### ISSUE TITLE
[Feature Request] Log into system temp folder

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/arcCommander#102]
Currently, logging is done by writing directly into the .arc folder of the arc. Maybe it might be better to write to a more global location like system specific temp folder?

**Comment by omaus** [comment]
Yes, but under that condition, the logs of all ARCs will be merged since the name is atm. always "ArcCommander.log". We would need to specify the name according to the ARC.

Don't know how all the OSs handle temp folders but it is likely that they are flushed from time to time (in newer Win 10 versions it is done automatically depending on user settings), leading to a maybe surprising absence of the logs after a while. Some programs that I know rather have their logs in local folders like `%localappdata%\<app>\` or `%localappdata%\<company>\<app>` (and corresponding in Unix).

**Comment by HLWeil** [comment]
The `logger` could specify the `workdir` in which the command is run. And yes `%localappdata%` seems much more sensible!

**Comment by HLWeil** [comment]
Hey @omaus, how is the progress on this?
