### ISSUE TITLE
[Feature Request] Latest and OS tags for releases 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/arcCommander#116]
**Is your feature request related to a problem? Please describe.**
The unix installations are currently a bit clicking back and forth. 
And we're tearing people into the terminal anyways, so let's make ArcCommander fully installable from there. 

**Describe the solution you'd like**
Is it possible to automagically get linked to the latest arc releases for a specific OS:
<https://github.com/nfdi4plants/arcCommander/releases/latest/>***macos***
<https://github.com/nfdi4plants/arcCommander/releases/latest/>***linux***

**Additional context**

I've tried to write out the linux installation a bit more click-and-copy.  
We'd just have to replace the "v0.2.1-linux.x64/arc" by e.g. "latest/linux.x64/arc" in the wget. 
Assuming that `wget` is installed on linux by default (not an expert). 

## Install ArcCommander on Linux

1. Download latest release

    ```bash
    wget https://github.com/nfdi4plants/arcCommander/releases/download/v0.2.1-linux.x64/arc
    ```

1. Make executable

    ```bash
    chmod a+x arc
    ```

1. Move to suitable place (e.g. in your home directory or to `/home/bin/` to make it accessible for all users)

    ```bash
    mkdir ~/ArcCommander # Create folder "ArcCommander" in your home directory 
    mv arc ~/ArcCommander # move executable to that folder
    ```

1. Add that place to your path. This allows you to start the ArcCommander from any folder. 

    ```bash
    export PATH=$PATH:~/ArcCommander
    ```

1. Test that ArcCommander is properly installed
    
    ```bash
    arc --version # check the current version 
    ```

    ```bash
    mkdir ~/testArc; cd ~/testArc # create a test folder in your home directory and change into it    
    arc init # initialize arc    
    ```

    ```bash
    cd ~/; rm -rf testArc # remove test folder    
    ```

**Comment by omaus** [comment]
>Is it possible to automagically get linked to the latest arc releases for a specific OS:
https://github.com/nfdi4plants/arcCommander/releases/latest/macos
https://github.com/nfdi4plants/arcCommander/releases/latest/linux

Afaik that's not possible, unfortunately.  
But we could move all releases into one release per OS, meaning that we'd always override the current one.  
_Downside:_ Impossible to get older releases without building the repo yourself.

---

![image](https://user-images.githubusercontent.com/47781170/157419568-7b5a386d-ed8e-47b0-b5a4-a6175d507715.png)

The URL is set to a specific release. But I think we can enhance the current GitHub action to also change this line in the README.md. Otherwise, we'd have to update the README.md with every release manually.  
Besides that, I like your suggestion.

**Comment by Brilator** [comment]
Shit, I had to look up *afaik*. :older_man:

If the gh action can take care of this, that would be perfect. Would probably also be easier for user trouble-shooting with the version specified rather than "latest".

**Comment by Brilator** [comment]
Reminder to automate installation (instructions). #136
