### ISSUE TITLE
[Feature Request] Scattered arc commander tutorials

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/arcCommander#149]
We currently have three different arc commander tutorials with a bit of overlap. 

1. GH Wiki - Experimentalist user journey: https://github.com/nfdi4plants/arcCommander/wiki/Exemplary-scenario-–-Experimentalist-user-journey
2. HP Deep dive: https://nfdi4plants.org/content/service/arccommander.html
3. Knowledge Base Quick Start: https://nfdi4plants.org/nfdi4plants.knowledgebase/docs/tutorials/QuickStart_arc.html

I don't mean to keep only one and delete the others. All three have different perspectives and intentions and they're all valuable, e.g. 

1. Experimentalist journey: here's what you can do, if somebody hands you an ARC. (although, here the example could be aligned with the other more [plant related example](https://nfdi4plants.org/nfdi4plants.knowledgebase/docs/fundamentals/Metadata.html) rather than zebra fish)
2. Deep dive: those are the major commands, explore for your own ARC.
3. Quickstart: If you exactly follow this hands-on, you have a working ARC.

However, for easier curation and more consistency I would suggest to merge or collect them at one place (my suggestion would be the knowledge base) and link from the previous places to there.

@Martin-Kuhl @HLWeil @omaus

**Comment by Martin-Kuhl** [comment]
I'm not sure if we really need the Deep dive in the future, as a well structured wiki (in the form of a docs page as discussed previously) and the QuickStart should be sufficient for most cases. Thus, it leads only to additinal workload in curating the page, as you already mentioned. Plus, I hope that we soon have a GUI so that we probably don't need to teach the command line anymore (more experienced users will be happy with a well structured wiki I guess). 

I would go with:
- QuickStart on KnowledgeBase and
- wiki on Docs page

**Comment by Brilator** [comment]
Last open task: 

- [ ] remove the deprecated deep dive https://nfdi4plants.org/content/service/arccommander.html 

@CMR248

**Comment by HLWeil** [comment]
Fixed in 
https://github.com/nfdi4plants/nfdi4plants.github.io/commit/238038928dd6cff99add77b05cd06d8b15448a3d
