### ISSUE TITLE
[Feature Request] `arc init` should also create parentfolder if not already existing

### ISSUE THREAD

**Issue by CMR248** [nfdi4plants/arcCommander#165]
The following idea came up during the 1st BioHackathon Germay:
In addition to the substructure, it would be useful if the *arc init* command would also create the parent folder. A feasible solution could be that the ARC Commander scans the specified place for existing folders with the corresponding title and creates a corresponding folder in the absence of such.

**Comment by omaus** [comment]
Atm., it is intentioned that the ArcCommander is always called from _inside_ an ARC root folder.

If we would build in your request, we might also need to change directory directly afterwards (inside the ARC root folder), otherwise subsequent `arc` commands won't work.  
From me perspective, we could do so though it's quite a change looking at the current behavior.

@HLWeil What do you think?

**Comment by HLWeil** [comment]
Actually I'm not 100% sure about this. As you mentioned, @omaus, the needed additional navigation into the folder might be annoying. Currently I implemented it like @CMR248 suggested: 
https://github.com/nfdi4plants/arcCommander/blob/d052577f1d640250851eb07a7ae57b1539ba4bb3/src/ArcCommander/APIs/ArcAPI.fs#L33
Will try it out a a bit. Also might add the automatic navigation into the folder.

**Comment by omaus** [comment]
What about `arc init` asks the user to give a name and if they don't (= leaves empty), it creates the ARC inside the current folder?
To have people still create ARCs quickly, we could add `--force`/`-f` to directly create the ARC structure inside the current folder (which is the current way it works).
