### ISSUE TITLE
[Feature Request] auto-increase post buffer for ARCs with large data files

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCCommander#176]
**Is your feature request related to a problem? Please describe.**
Not sure, if I'm doing something wrong, but my `arc sync` sometimes hangs during or after "writing objects" or when trying to pusher "larger" (less than 0.5GB) files that are not automatically git-lfs tracked. 

**Describe the solution you'd like**
It usually helped to increase the http buffer (see https://github.com/nfdi4plants/nfdi4plants.knowledgebase/issues/65). 

Might be worth to let ARC commander do this automagically when detecting relevant files.

**Comment by HLWeil** [comment]
Hey, thanks for bringing up this issue and also the possible solution. By googling around a bit, I saw that this issue is especially prevalent for people trying to use git-clone. This makes it a bit harder to implement this in an automagical way.

Also, this issue is specific for non-lfs files, which wouldn't be the encouraged way to handle >100mb files anyways.

Maybe just put this into a FAQ section of the knowledgebase instead?

**Comment by Brilator** [comment]
> this issue is specific for non-lfs files, which wouldn't be the encouraged way to handle >100mb files 

agreed
