### ISSUE TITLE
Arc commander not working on Ubuntu 16.04

### ISSUE THREAD

**Issue by HajiraJabeen** [nfdi4plants/arcCommander#41]
The execution of bash.sh shows a few exceptions and finally, exits on pressing any key
"parse_git_dirty:8: DISABLE_UNTRACKED_FILES_DIRTY: parameter not set "
/.../arcCommander/build.fsx (146,12)-(146,26): FSharpErrorSeverity.Warning FS1182: The value 'standardParams' is unused
/.../arcCommander/build.fsx (194,32)-(194,45): FSharpErrorSeverity.Warning FS1182: The value 'msBuildParams' is unused
Warning: Paket resolved a FSharp.Core with version '5.0.0.0', but fake runs with a version of '4.7.0.0'. This is not supported.
Please either lock the version via 'nuget FSharp.Core <nuget-version>' or upgrade fake.
Read https://github.com/fsharp/FAKE/issues/2001 for details.
Hint: The fake-runner has not been updated for at least 6 months. Please consider upgrading to get latest bugfixes, improved suggestions and F# features.

**Comment by kMutagene** [comment]
also, did you follow these steps if you want to build the binaries yourself? https://github.com/nfdi4plants/arcCommander#develop

**Comment by kMutagene** [comment]
I see, we need to adapt the instructions there. You need the 3.1 .NET runtime for executing the binaries, so it is best to just install the 3.1 SDK (you only have 5.0.5): https://dotnet.microsoft.com/download/dotnet/3.1. 

You still do not have to build the binaries yourself if you only want to test the command line tool, the published binaries should be self contained and not require any setup. 

The build target `realease` fails for you by design, because you can not push the binaries to package registries. Please use `CopyBinaries` or just `Build`. Seems like the build completed successfully for you anyways, so installing above SDK should do the trick.

**Comment by HajiraJabeen** [comment]
Thanks, works with 3.1,
I suggest it should be updated in the prerequisites ".NET SDK >= 3.1.00 (should roll forward to .net 5 if you are using that)"

**Comment by kMutagene** [comment]
The new readme should clarify every issue that came up here ;)
