### ISSUE TITLE
[Feature request] Let "update" do "register" if item does not exist. 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/arcCommander#44]
For example if a publication does not exist, I would suggest that an update would just initiate a registration, e.g. 
let 

```
arc i publication update -d 2021_ARC05_Pub01tmp --title "Review on yeast P09 protein and its involvement
 in redox susceptibility"
```

do:

```
arc i publication register -d 2021_ARC05_Pub01tmp --title "Review on yeast P09 protein and its involvement
 in redox susceptibility"
```

**Comment by HLWeil** [comment]
Hey,

Yes that's a good idea, however I think the user should have control about this. E.g. a `--force / -f` or a `--addifmissing` flag might be added to the arguments.

What do you think, @Brilator?

**Comment by HLWeil** [comment]
I added such a `--addifmissing` flag in 1825606685d3b5bda083a02e5399882e5ae8005f. Making use of this flag is kind of a proactive move, possibly preventing loss of changes to be made. 
Some kind of reactive capability seems sensible too, in order to make the program a little bit more forgiving towards mistakes. Maybe some kind of `y/n` cli query. Alternatively the planned addition of a logger library might do the trick too.
