### ISSUE TITLE
[BUG] (person) update not working properly

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/arcCommander#54]
**Describe the bug**
Updating info via CLI does not work for me. 

**To Reproduce**
1. `arc i person register -f "An" -m "other" -l "person" --roles "MSc"`
2. `arc i person update -f "An" -m "other" -l "person" --roles "PhD"`
3. Error: 
```
...
Start Person Update
Person with the name An other person does not exist in the investigation
Done processing command
```

**OS and framework information (please complete the following information):**
- OS: MacOS Big Sur
- OS Version 11.3.1

**Comment by Brilator** [comment]
This is specific to person, as the following works: 
 
```
arc s add --identifier SomeStudy --submissiondate "tomorrow"
arc s update --identifier SomeStudy --submissiondate "some time in the far future"
```

```
arc a add -s SomeStudy -a SomeAssay --measurementtype RNASeq
arc a update -s SomeStudy -a SomeAssay --measurementtype mRNASeq
```

**Comment by HLWeil** [comment]
I identified the [faulty line](https://github.com/nfdi4plants/arcCommander/blob/developer/src/ArcCommander/APIs/InvestigationAPI.fs#L149)

The same error exists in the [study contacts update command](https://github.com/nfdi4plants/arcCommander/blob/developer/src/ArcCommander/APIs/StudyAPI.fs#L301)

Will be fixed in the next bug-fix round
